### ISSUE TITLE
Not documented well that this is the true default theme

### ISSUE THREAD

**Issue by DavidGriswoldTeacher** [pages-themes/primer#34]
I should probably put this issue in the repository of the github help documentation, but I'm not sure where that is.

Just wanted to report that it took me about an hour of intensive searching and trial-and-error to realize that this is the theme that Github Pages uses if you don't put a theme in your _config.yml. I think that should be more clearly documented in the Github Pages documentation. I love the simplicity of the theme but wanted to make just one tiny tweak to the default layout, and it took me a very long time to figure out that this was the default.html file I needed to find!

**Comment by ff4f01** [comment]
@DavidGriswoldTeacher I went through an exactly same trial-and-error as you did. I also think it is crucial for the users to know this is the default theme. Opened a PR https://github.com/pages-themes/primer/pull/37 and let's see how it goes :)
