### ISSUE TITLE
Table Of Content (TOC) support

### ISSUE THREAD

**Issue by zimbatm** [pages-themes/primer#39]
For long posts, it would be nice if the theme supported generating a table of content from the markdown document.

Maybe with a `toc: true` in the frontmatter?

**Comment by seshrs** [comment]
@zimbatm I had a use case that also required generating a table of contents. I felt it may not necessarily fit the minimalist spirit of Primer, so I forked my changes to a new theme, [eecs485staff/primer-spec](github.com/eecs485staff/primer-spec). 

I’m not sure if it would work for your use case, but feel free to use it if it does!

**Comment by zimbatm** [comment]
thanks for the pointer!
